### PR TITLE
Add top-k training and aydao's mega config

### PR DESCRIPTION
**Pull request by JCBrouwer**
I've added aydao's config as he's described in the TPU Podcast Discord. This is what he used to train the model in [this tweet](https://twitter.com/AydaoGMan/status/1326641676065136641).

It disables path length and style mixing regularization, doubles the size of the generator, and uses top-k training (leaving the discriminator default).

### CODE REVIEW

**Comment by YukiSakuma** [comment]
Very interesting hack, does the added top-k training work on any square resolution or only for 512x512 images?
Could this also train well on a low number (500-1000) dataset but diverse images?

**Comment by JCBrouwer** [comment]
> Very interesting hack, does the added top-k training work on any square resolution or only for 512x512 images?
> Could this also train well on a low number (500-1000) dataset but diverse images?

Top-k training should be beneficial in all cases (square or non-square doesn't matter, it's batchwise), although it works better with larger batch sizes (=> it's actually more beneficial for smaller image sizes as your batch size can be bigger).

One thing to note is that the exponential decay is set pretty long with default settings (1/4 of training to decay to half the batch, which by default is 6250 kimg). For small datasets you'll be training for a relatively very short time, so you'll need to set the top_k_gamma lower or set the max number of kimg to something realistic (~300 should be fine if you're transfer learning, more if you're starting from scratch).

The formula is: fraction_of_batch_used = top_k_gamma^percent_of_training_complete. Once the fraction reaches top_k_frac it stays constant.

The other important part of aydao's config is doubling the parameter count of the generator, this part is only useful for very large datasets.

**Comment by YukiSakuma** [comment]
> > Very interesting hack, does the added top-k training work on any square resolution or only for 512x512 images?
> > Could this also train well on a low number (500-1000) dataset but diverse images?
> 
> Top-k training should be beneficial in all cases (square or non-square doesn't matter, it's batchwise), although it works better with larger batch sizes (=> it's actually more beneficial for smaller image sizes as your batch size can be bigger).
> 
> One thing to note is that the exponential decay is set pretty long with default settings (1/4 of training to decay to half the batch, which by default is 6250 kimg). For small datasets you'll be training for a relatively very short time, so you'll need to set the top_k_gamma lower or set the max number of kimg to something realistic (~300 should be fine if you're transfer learning, more if you're starting from scratch).
> 
> The formula is: fraction_of_batch_used = top_k_gamma^percent_of_training_complete. Once the fraction reaches top_k_frac it stays constant.
> 
> The other important part of aydao's config is doubling the parameter count of the generator, this part is only useful for very large datasets.

Nice thanks for the tips, but when I am trying to train using 512x512 images from transfer learning I get this error at the start of the training
```
Traceback (most recent call last):
  File "train.py", line 615, in <module>
    main()
  File "train.py", line 607, in main
    run_training(**vars(args))
  File "train.py", line 497, in run_training
    training_loop.training_loop(**training_options)
  File "/content/stylegan2-ada-main/training/training_loop.py", line 156, in training_loop
    G.copy_vars_from(rG)
  File "/content/stylegan2-ada-main/dnnlib/tflib/network.py", line 512, in copy_vars_from
    self._components[name].copy_vars_from(src_comp)
  File "/content/stylegan2-ada-main/dnnlib/tflib/network.py", line 509, in copy_vars_from
    self.copy_own_vars_from(src_net)
  File "/content/stylegan2-ada-main/dnnlib/tflib/network.py", line 482, in copy_own_vars_from
    tfutil.set_vars({self._get_vars()[name]: value for name, value in value_dict.items() if name in self._get_vars()})
  File "/content/stylegan2-ada-main/dnnlib/tflib/tfutil.py", line 227, in set_vars
    run(ops, feed_dict)
  File "/content/stylegan2-ada-main/dnnlib/tflib/tfutil.py", line 33, in run
    return tf.get_default_session().run(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1156, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 512, 4, 4) for Tensor 'G_synthesis/4x4/Const/const/new_value:0', which has shape '(1, 1024, 4, 4)'
```

Any help?

**Comment by YukiSakuma** [comment]
Setting the `resume` to `noresume ` gets past the error, but if possible I don't really want to train from scratch (currently I set it to 2500 kimg). Is there a pretrained model available to use that was trained from aydao config? Or is there a script surgery that converts a pretrained model to make it compatible with aydao config?


Edit: Do I really need to use aydao's config? I only have 700 images to train but a diverse/complex one, is it better to use `11gb-gpu-complex` instead? Will I really miss out if I don't use aydao's config?

**Comment by JCBrouwer** [comment]
There's no pretrained version of aydao's config, but you don't need to use aydao's config. With 700 images it won't give very good results.

To use top-k training without the config (which might give you a small benefit), you can copy [lines 225-230 in train.py](https://github.com/dvschultz/stylegan2-ada/blob/main/train.py#L225) just outside of the if-statement and then use whatever config you like (11gb-gpu-complex is good). Make sure you set args.total_kimg to something realistic as well ~500-1000 for transfer learning.

If you really wanted to transfer learn with the larger model, you could use aydao's [stylegan2-surgery repo](https://github.com/aydao/stylegan2-surgery) to create a new network with the correct shapes and then copy the pretrained weights into the first half of the parameters, but the results probably won't be stellar.

**Pull request merged**
